import json

countries_by_continent = {
    "all": [
        {"name": "Nigeria", "flag": "https://flagcdn.com/w320/ng.png", "aliases": []},
        {"name": "Ethiopia", "flag": "https://flagcdn.com/w320/et.png", "aliases": []},
        {"name": "Egypt", "flag": "https://flagcdn.com/w320/eg.png", "aliases": []},
        {"name": "DR Congo", "flag": "https://flagcdn.com/w320/cd.png", "aliases": ['Democratic Republic of the Congo', 'DRC']},
        {"name": "Tanzania", "flag": "https://flagcdn.com/w320/tz.png", "aliases": []},
        {"name": "South Africa", "flag": "https://flagcdn.com/w320/za.png", "aliases": []},
        {"name": "Kenya", "flag": "https://flagcdn.com/w320/ke.png", "aliases": []},
        {"name": "Uganda", "flag": "https://flagcdn.com/w320/ug.png", "aliases": []},
        {"name": "Algeria", "flag": "https://flagcdn.com/w320/dz.png", "aliases": []},
        {"name": "Sudan", "flag": "https://flagcdn.com/w320/sd.png", "aliases": []},
        {"name": "Morocco", "flag": "https://flagcdn.com/w320/ma.png", "aliases": []},
        {"name": "Angola", "flag": "https://flagcdn.com/w320/ao.png", "aliases": []},
        {"name": "Mozambique", "flag": "https://flagcdn.com/w320/mz.png", "aliases": []},
        {"name": "Ghana", "flag": "https://flagcdn.com/w320/gh.png", "aliases": []},
        {"name": "Madagascar", "flag": "https://flagcdn.com/w320/mg.png", "aliases": []},
        {"name": "Cameroon", "flag": "https://flagcdn.com/w320/cm.png", "aliases": []},
        {"name": "Côte d'Ivoire", "flag": "https://flagcdn.com/w320/ci.png", "aliases": ["Ivory Coast"]},
        {"name": "Niger", "flag": "https://flagcdn.com/w320/ne.png", "aliases": []},
        {"name": "Burkina Faso", "flag": "https://flagcdn.com/w320/bf.png", "aliases": []},
        {"name": "Mali", "flag": "https://flagcdn.com/w320/ml.png", "aliases": []},
        {"name": "Malawi", "flag": "https://flagcdn.com/w320/mw.png", "aliases": []},
        {"name": "Zambia", "flag": "https://flagcdn.com/w320/zm.png", "aliases": []},
        {"name": "Senegal", "flag": "https://flagcdn.com/w320/sn.png", "aliases": []},
        {"name": "Chad", "flag": "https://flagcdn.com/w320/td.png", "aliases": []},
        {"name": "Somalia", "flag": "https://flagcdn.com/w320/so.png", "aliases": []},
        {"name": "Zimbabwe", "flag": "https://flagcdn.com/w320/zw.png", "aliases": []},
        {"name": "Guinea", "flag": "https://flagcdn.com/w320/gn.png", "aliases": []},
        {"name": "Rwanda", "flag": "https://flagcdn.com/w320/rw.png", "aliases": []},
        {"name": "Benin", "flag": "https://flagcdn.com/w320/bj.png", "aliases": []},
        {"name": "Burundi", "flag": "https://flagcdn.com/w320/bi.png", "aliases": []},
        {"name": "Tunisia", "flag": "https://flagcdn.com/w320/tn.png", "aliases": []},
        {"name": "South Sudan", "flag": "https://flagcdn.com/w320/ss.png", "aliases": []},
        {"name": "Togo", "flag": "https://flagcdn.com/w320/tg.png", "aliases": []},
        {"name": "Sierra Leone", "flag": "https://flagcdn.com/w320/sl.png", "aliases": []},
        {"name": "Libya", "flag": "https://flagcdn.com/w320/ly.png", "aliases": []},
        {"name": "Congo", "flag": "https://flagcdn.com/w320/cg.png", "aliases": []},
        {"name": "Liberia", "flag": "https://flagcdn.com/w320/lr.png", "aliases": []},
        {"name": "Central African Republic", "flag": "https://flagcdn.com/w320/cf.png", "aliases": ["CAR"]},
        {"name": "Mauritania", "flag": "https://flagcdn.com/w320/mr.png", "aliases": []},
        {"name": "Eritrea", "flag": "https://flagcdn.com/w320/er.png", "aliases": []},
        {"name": "Namibia", "flag": "https://flagcdn.com/w320/na.png", "aliases": []},
        {"name": "Gambia", "flag": "https://flagcdn.com/w320/gm.png", "aliases": []},
        {"name": "Botswana", "flag": "https://flagcdn.com/w320/bw.png", "aliases": []},
        {"name": "Gabon", "flag": "https://flagcdn.com/w320/ga.png", "aliases": []},
        {"name": "Lesotho", "flag": "https://flagcdn.com/w320/ls.png", "aliases": []},
        {"name": "Guinea-Bissau", "flag": "https://flagcdn.com/w320/gw.png", "aliases": []},
        {"name": "Equatorial Guinea", "flag": "https://flagcdn.com/w320/gq.png", "aliases": []},
        {"name": "Mauritius", "flag": "https://flagcdn.com/w320/mu.png", "aliases": []},
        {"name": "Eswatini", "flag": "https://flagcdn.com/w320/sz.png", "aliases": ["Swaziland"]},
        {"name": "Djibouti", "flag": "https://flagcdn.com/w320/dj.png", "aliases": []},
        {"name": "Comoros", "flag": "https://flagcdn.com/w320/km.png", "aliases": []},
        {"name": "Cabo Verde", "flag": "https://flagcdn.com/w320/cv.png", "aliases": ["Cape Verde"]},
        {"name": "Sao Tome and Principe", "flag": "https://flagcdn.com/w320/st.png", "aliases": []},
        {"name": "Seychelles", "flag": "https://flagcdn.com/w320/sc.png", "aliases": []},
        {"name": "China", "flag": "https://flagcdn.com/w320/cn.png", "aliases": ["PRC"]},
        {"name": "India", "flag": "https://flagcdn.com/w320/in.png", "aliases": []},
        {"name": "Indonesia", "flag": "https://flagcdn.com/w320/id.png", "aliases": []},
        {"name": "Pakistan", "flag": "https://flagcdn.com/w320/pk.png", "aliases": []},
        {"name": "Bangladesh", "flag": "https://flagcdn.com/w320/bd.png", "aliases": []},
        {"name": "Japan", "flag": "https://flagcdn.com/w320/jp.png", "aliases": []},
        {"name": "Philippines", "flag": "https://flagcdn.com/w320/ph.png", "aliases": []},
        {"name": "Vietnam", "flag": "https://flagcdn.com/w320/vn.png", "aliases": []},
        {"name": "Turkey", "flag": "https://flagcdn.com/w320/tr.png", "aliases": []},
        {"name": "Iran", "flag": "https://flagcdn.com/w320/ir.png", "aliases": []},
        {"name": "Thailand", "flag": "https://flagcdn.com/w320/th.png", "aliases": []},
        {"name": "South Korea", "flag": "https://flagcdn.com/w320/kr.png", "aliases": ["Korea"]},
        {"name": "Iraq", "flag": "https://flagcdn.com/w320/iq.png", "aliases": []},
        {"name": "Afghanistan", "flag": "https://flagcdn.com/w320/af.png", "aliases": []},
        {"name": "Saudi Arabia", "flag": "https://flagcdn.com/w320/sa.png", "aliases": []},
        {"name": "Uzbekistan", "flag": "https://flagcdn.com/w320/uz.png", "aliases": []},
        {"name": "Malaysia", "flag": "https://flagcdn.com/w320/my.png", "aliases": []},
        {"name": "Yemen", "flag": "https://flagcdn.com/w320/ye.png", "aliases": []},
        {"name": "Nepal", "flag": "https://flagcdn.com/w320/np.png", "aliases": []},
        {"name": "North Korea", "flag": "https://flagcdn.com/w320/kp.png", "aliases": ["DPRK"]},
        {"name": "Sri Lanka", "flag": "https://flagcdn.com/w320/lk.png", "aliases": []},
        {"name": "Kazakhstan", "flag": "https://flagcdn.com/w320/kz.png", "aliases": []},
        {"name": "Syria", "flag": "https://flagcdn.com/w320/sy.png", "aliases": []},
        {"name": "Cambodia", "flag": "https://flagcdn.com/w320/kh.png", "aliases": []},
        {"name": "Jordan", "flag": "https://flagcdn.com/w320/jo.png", "aliases": []},
        {"name": "Azerbaijan", "flag": "https://flagcdn.com/w320/az.png", "aliases": []},
        {"name": "United Arab Emirates", "flag": "https://flagcdn.com/w320/ae.png", "aliases": ["UAE"]},
        {"name": "Tajikistan", "flag": "https://flagcdn.com/w320/tj.png", "aliases": []},
        {"name": "Israel", "flag": "https://flagcdn.com/w320/il.png", "aliases": []},
        {"name": "Laos", "flag": "https://flagcdn.com/w320/la.png", "aliases": []},
        {"name": "Lebanon", "flag": "https://flagcdn.com/w320/lb.png", "aliases": []},
        {"name": "Kyrgyzstan", "flag": "https://flagcdn.com/w320/kg.png", "aliases": []},
        {"name": "Turkmenistan", "flag": "https://flagcdn.com/w320/tm.png", "aliases": []},
        {"name": "Singapore", "flag": "https://flagcdn.com/w320/sg.png", "aliases": []},
        {"name": "Oman", "flag": "https://flagcdn.com/w320/om.png", "aliases": []},
        {"name": "State of Palestine", "flag": "https://flagcdn.com/w320/ps.png", "aliases": ["Palestine"]},
        {"name": "Kuwait", "flag": "https://flagcdn.com/w320/kw.png", "aliases": []},
        {"name": "Georgia", "flag": "https://flagcdn.com/w320/ge.png", "aliases": []},
        {"name": "Mongolia", "flag": "https://flagcdn.com/w320/mn.png", "aliases": []},
        {"name": "Armenia", "flag": "https://flagcdn.com/w320/am.png", "aliases": []},
        {"name": "Qatar", "flag": "https://flagcdn.com/w320/qa.png", "aliases": []},
        {"name": "Bahrain", "flag": "https://flagcdn.com/w320/bh.png", "aliases": []},
        {"name": "Timor-Leste", "flag": "https://flagcdn.com/w320/tl.png", "aliases": ["East Timor", 'Timor']},
        {"name": "Cyprus", "flag": "https://flagcdn.com/w320/cy.png", "aliases": []},
        {"name": "Bhutan", "flag": "https://flagcdn.com/w320/bt.png", "aliases": []},
        {"name": "Maldives", "flag": "https://flagcdn.com/w320/mv.png", "aliases": []},
        {"name": "Brunei", "flag": "https://flagcdn.com/w320/bn.png", "aliases": []},
        {"name": "Russia", "flag": "https://flagcdn.com/w320/ru.png", "aliases": []},
        {"name": "Germany", "flag": "https://flagcdn.com/w320/de.png", "aliases": []},
        {"name": "United Kingdom", "flag": "https://flagcdn.com/w320/gb.png", "aliases": ["UK", "Britain"]},
        {"name": "France", "flag": "https://flagcdn.com/w320/fr.png", "aliases": []},
        {"name": "Italy", "flag": "https://flagcdn.com/w320/it.png", "aliases": []},
        {"name": "Spain", "flag": "https://flagcdn.com/w320/es.png", "aliases": []},
        {"name": "Ukraine", "flag": "https://flagcdn.com/w320/ua.png", "aliases": []},
        {"name": "Poland", "flag": "https://flagcdn.com/w320/pl.png", "aliases": []},
        {"name": "Romania", "flag": "https://flagcdn.com/w320/ro.png", "aliases": []},
        {"name": "Netherlands", "flag": "https://flagcdn.com/w320/nl.png", "aliases": []},
        {"name": "Belgium", "flag": "https://flagcdn.com/w320/be.png", "aliases": []},
        {"name": "Czech Republic", "flag": "https://flagcdn.com/w320/cz.png", "aliases": ["Czechia"]},
        {"name": "Greece", "flag": "https://flagcdn.com/w320/gr.png", "aliases": []},
        {"name": "Portugal", "flag": "https://flagcdn.com/w320/pt.png", "aliases": []},
        {"name": "Sweden", "flag": "https://flagcdn.com/w320/se.png", "aliases": []},
        {"name": "Hungary", "flag": "https://flagcdn.com/w320/hu.png", "aliases": []},
        {"name": "Belarus", "flag": "https://flagcdn.com/w320/by.png", "aliases": []},
        {"name": "Austria", "flag": "https://flagcdn.com/w320/at.png", "aliases": []},
        {"name": "Serbia", "flag": "https://flagcdn.com/w320/rs.png", "aliases": []},
        {"name": "Switzerland", "flag": "https://flagcdn.com/w320/ch.png", "aliases": []},
        {"name": "Bulgaria", "flag": "https://flagcdn.com/w320/bg.png", "aliases": []},
        {"name": "Denmark", "flag": "https://flagcdn.com/w320/dk.png", "aliases": []},
        {"name": "Finland", "flag": "https://flagcdn.com/w320/fi.png", "aliases": []},
        {"name": "Slovakia", "flag": "https://flagcdn.com/w320/sk.png", "aliases": []},
        {"name": "Norway", "flag": "https://flagcdn.com/w320/no.png", "aliases": []},
        {"name": "Ireland", "flag": "https://flagcdn.com/w320/ie.png", "aliases": []},
        {"name": "Croatia", "flag": "https://flagcdn.com/w320/hr.png", "aliases": []},
        {"name": "Moldova", "flag": "https://flagcdn.com/w320/md.png", "aliases": []},
        {"name": "Bosnia and Herzegovina", "flag": "https://flagcdn.com/w320/ba.png", "aliases": []},
        {"name": "Albania", "flag": "https://flagcdn.com/w320/al.png", "aliases": []},
        {"name": "Lithuania", "flag": "https://flagcdn.com/w320/lt.png", "aliases": []},
        {"name": "North Macedonia", "flag": "https://flagcdn.com/w320/mk.png", "aliases": ["Macedonia"]},
        {"name": "Slovenia", "flag": "https://flagcdn.com/w320/si.png", "aliases": []},
        {"name": "Latvia", "flag": "https://flagcdn.com/w320/lv.png", "aliases": []},
        {"name": "Estonia", "flag": "https://flagcdn.com/w320/ee.png", "aliases": []},
        {"name": "Montenegro", "flag": "https://flagcdn.com/w320/me.png", "aliases": []},
        {"name": "Luxembourg", "flag": "https://flagcdn.com/w320/lu.png", "aliases": []},
        {"name": "Malta", "flag": "https://flagcdn.com/w320/mt.png", "aliases": []},
        {"name": "Iceland", "flag": "https://flagcdn.com/w320/is.png", "aliases": []},
        {"name": "Andorra", "flag": "https://flagcdn.com/w320/ad.png", "aliases": []},
        {"name": "Monaco", "flag": "https://flagcdn.com/w320/mc.png", "aliases": []},
        {"name": "Liechtenstein", "flag": "https://flagcdn.com/w320/li.png", "aliases": []},
        {"name": "San Marino", "flag": "https://flagcdn.com/w320/sm.png", "aliases": []},
        {"name": "Holy See", "flag": "https://flagcdn.com/w320/va.png", "aliases": ["Vatican City"]},
        {"name": "United States", "flag": "https://flagcdn.com/w320/us.png", "aliases": ["USA", "America"]},
        {"name": "Mexico", "flag": "https://flagcdn.com/w320/mx.png", "aliases": []},
        {"name": "Canada", "flag": "https://flagcdn.com/w320/ca.png", "aliases": []},
        {"name": "Guatemala", "flag": "https://flagcdn.com/w320/gt.png", "aliases": []},
        {"name": "Haiti", "flag": "https://flagcdn.com/w320/ht.png", "aliases": []},
        {"name": "Cuba", "flag": "https://flagcdn.com/w320/cu.png", "aliases": []},
        {"name": "Dominican Republic", "flag": "https://flagcdn.com/w320/do.png", "aliases": []},
        {"name": "Honduras", "flag": "https://flagcdn.com/w320/hn.png", "aliases": []},
        {"name": "El Salvador", "flag": "https://flagcdn.com/w320/sv.png", "aliases": []},
        {"name": "Nicaragua", "flag": "https://flagcdn.com/w320/ni.png", "aliases": []},
        {"name": "Costa Rica", "flag": "https://flagcdn.com/w320/cr.png", "aliases": []},
        {"name": "Panama", "flag": "https://flagcdn.com/w320/pa.png", "aliases": []},
        {"name": "Jamaica", "flag": "https://flagcdn.com/w320/jm.png", "aliases": []},
        {"name": "Trinidad and Tobago", "flag": "https://flagcdn.com/w320/tt.png", "aliases": []},
        {"name": "Bahamas", "flag": "https://flagcdn.com/w320/bs.png", "aliases": []},
        {"name": "Belize", "flag": "https://flagcdn.com/w320/bz.png", "aliases": []},
        {"name": "Barbados", "flag": "https://flagcdn.com/w320/bb.png", "aliases": []},
        {"name": "Saint Lucia", "flag": "https://flagcdn.com/w320/lc.png", "aliases": []},
        {"name": "Grenada", "flag": "https://flagcdn.com/w320/gd.png", "aliases": []},
        {"name": "Saint Vincent and the Grenadines", "flag": "https://flagcdn.com/w320/vc.png", "aliases": []},
        {"name": "Antigua and Barbuda", "flag": "https://flagcdn.com/w320/ag.png", "aliases": []},
        {"name": "Saint Kitts and Nevis", "flag": "https://flagcdn.com/w320/kn.png", "aliases": []},
        {"name": "Dominica", "flag": "https://flagcdn.com/w320/dm.png", "aliases": []},
        {"name": "Brazil", "flag": "https://flagcdn.com/w320/br.png", "aliases": []},
        {"name": "Colombia", "flag": "https://flagcdn.com/w320/co.png", "aliases": []},
        {"name": "Argentina", "flag": "https://flagcdn.com/w320/ar.png", "aliases": []},
        {"name": "Peru", "flag": "https://flagcdn.com/w320/pe.png", "aliases": []},
        {"name": "Venezuela", "flag": "https://flagcdn.com/w320/ve.png", "aliases": []},
        {"name": "Chile", "flag": "https://flagcdn.com/w320/cl.png", "aliases": []},
        {"name": "Ecuador", "flag": "https://flagcdn.com/w320/ec.png", "aliases": []},
        {"name": "Bolivia", "flag": "https://flagcdn.com/w320/bo.png", "aliases": []},
        {"name": "Paraguay", "flag": "https://flagcdn.com/w320/py.png", "aliases": []},
        {"name": "Uruguay", "flag": "https://flagcdn.com/w320/uy.png", "aliases": []},
        {"name": "Guyana", "flag": "https://flagcdn.com/w320/gy.png", "aliases": []},
        {"name": "Suriname", "flag": "https://flagcdn.com/w320/sr.png", "aliases": []},
        {"name": "Australia", "flag": "https://flagcdn.com/w320/au.png", "aliases": []},
        {"name": "Papua New Guinea", "flag": "https://flagcdn.com/w320/pg.png", "aliases": []},
        {"name": "New Zealand", "flag": "https://flagcdn.com/w320/nz.png", "aliases": []},
        {"name": "Fiji", "flag": "https://flagcdn.com/w320/fj.png", "aliases": []},
        {"name": "Solomon Islands", "flag": "https://flagcdn.com/w320/sb.png", "aliases": []},
        {"name": "Micronesia", "flag": "https://flagcdn.com/w320/fm.png", "aliases": []},
        {"name": "Vanuatu", "flag": "https://flagcdn.com/w320/vu.png", "aliases": []},
        {"name": "Samoa", "flag": "https://flagcdn.com/w320/ws.png", "aliases": []},
        {"name": "Kiribati", "flag": "https://flagcdn.com/w320/ki.png", "aliases": []},
        {"name": "Tonga", "flag": "https://flagcdn.com/w320/to.png", "aliases": []},
        {"name": "Marshall Islands", "flag": "https://flagcdn.com/w320/mh.png", "aliases": []},
        {"name": "Palau", "flag": "https://flagcdn.com/w320/pw.png", "aliases": []},
        {"name": "Tuvalu", "flag": "https://flagcdn.com/w320/tv.png", "aliases": []},
        {"name": "Nauru", "flag": "https://flagcdn.com/w320/nr.png", "aliases": []},
    ],
    "africa": [
        {"name": "Nigeria", "flag": "https://flagcdn.com/w320/ng.png", "aliases": []},
        {"name": "Ethiopia", "flag": "https://flagcdn.com/w320/et.png", "aliases": []},
        {"name": "Egypt", "flag": "https://flagcdn.com/w320/eg.png", "aliases": []},
        {"name": "DR Congo", "flag": "https://flagcdn.com/w320/cd.png", "aliases": ['Democratic Republic of the Congo', 'DRC']},
        {"name": "Tanzania", "flag": "https://flagcdn.com/w320/tz.png", "aliases": []},
        {"name": "South Africa", "flag": "https://flagcdn.com/w320/za.png", "aliases": []},
        {"name": "Kenya", "flag": "https://flagcdn.com/w320/ke.png", "aliases": []},
        {"name": "Uganda", "flag": "https://flagcdn.com/w320/ug.png", "aliases": []},
        {"name": "Algeria", "flag": "https://flagcdn.com/w320/dz.png", "aliases": []},
        {"name": "Sudan", "flag": "https://flagcdn.com/w320/sd.png", "aliases": []},
        {"name": "Morocco", "flag": "https://flagcdn.com/w320/ma.png", "aliases": []},
        {"name": "Angola", "flag": "https://flagcdn.com/w320/ao.png", "aliases": []},
        {"name": "Mozambique", "flag": "https://flagcdn.com/w320/mz.png", "aliases": []},
        {"name": "Ghana", "flag": "https://flagcdn.com/w320/gh.png", "aliases": []},
        {"name": "Madagascar", "flag": "https://flagcdn.com/w320/mg.png", "aliases": []},
        {"name": "Cameroon", "flag": "https://flagcdn.com/w320/cm.png", "aliases": []},
        {"name": "Côte d'Ivoire", "flag": "https://flagcdn.com/w320/ci.png", "aliases": ["Ivory Coast"]},
        {"name": "Niger", "flag": "https://flagcdn.com/w320/ne.png", "aliases": []},
        {"name": "Burkina Faso", "flag": "https://flagcdn.com/w320/bf.png", "aliases": []},
        {"name": "Mali", "flag": "https://flagcdn.com/w320/ml.png", "aliases": []},
        {"name": "Malawi", "flag": "https://flagcdn.com/w320/mw.png", "aliases": []},
        {"name": "Zambia", "flag": "https://flagcdn.com/w320/zm.png", "aliases": []},
        {"name": "Senegal", "flag": "https://flagcdn.com/w320/sn.png", "aliases": []},
        {"name": "Chad", "flag": "https://flagcdn.com/w320/td.png", "aliases": []},
        {"name": "Somalia", "flag": "https://flagcdn.com/w320/so.png", "aliases": []},
        {"name": "Zimbabwe", "flag": "https://flagcdn.com/w320/zw.png", "aliases": []},
        {"name": "Guinea", "flag": "https://flagcdn.com/w320/gn.png", "aliases": []},
        {"name": "Rwanda", "flag": "https://flagcdn.com/w320/rw.png", "aliases": []},
        {"name": "Benin", "flag": "https://flagcdn.com/w320/bj.png", "aliases": []},
        {"name": "Burundi", "flag": "https://flagcdn.com/w320/bi.png", "aliases": []},
        {"name": "Tunisia", "flag": "https://flagcdn.com/w320/tn.png", "aliases": []},
        {"name": "South Sudan", "flag": "https://flagcdn.com/w320/ss.png", "aliases": []},
        {"name": "Togo", "flag": "https://flagcdn.com/w320/tg.png", "aliases": []},
        {"name": "Sierra Leone", "flag": "https://flagcdn.com/w320/sl.png", "aliases": []},
        {"name": "Libya", "flag": "https://flagcdn.com/w320/ly.png", "aliases": []},
        {"name": "Congo", "flag": "https://flagcdn.com/w320/cg.png", "aliases": []},
        {"name": "Liberia", "flag": "https://flagcdn.com/w320/lr.png", "aliases": []},
        {"name": "Central African Republic", "flag": "https://flagcdn.com/w320/cf.png", "aliases": ["CAR"]},
        {"name": "Mauritania", "flag": "https://flagcdn.com/w320/mr.png", "aliases": []},
        {"name": "Eritrea", "flag": "https://flagcdn.com/w320/er.png", "aliases": []},
        {"name": "Namibia", "flag": "https://flagcdn.com/w320/na.png", "aliases": []},
        {"name": "Gambia", "flag": "https://flagcdn.com/w320/gm.png", "aliases": []},
        {"name": "Botswana", "flag": "https://flagcdn.com/w320/bw.png", "aliases": []},
        {"name": "Gabon", "flag": "https://flagcdn.com/w320/ga.png", "aliases": []},
        {"name": "Lesotho", "flag": "https://flagcdn.com/w320/ls.png", "aliases": []},
        {"name": "Guinea-Bissau", "flag": "https://flagcdn.com/w320/gw.png", "aliases": []},
        {"name": "Equatorial Guinea", "flag": "https://flagcdn.com/w320/gq.png", "aliases": []},
        {"name": "Mauritius", "flag": "https://flagcdn.com/w320/mu.png", "aliases": []},
        {"name": "Eswatini", "flag": "https://flagcdn.com/w320/sz.png", "aliases": ["Swaziland"]},
        {"name": "Djibouti", "flag": "https://flagcdn.com/w320/dj.png", "aliases": []},
        {"name": "Comoros", "flag": "https://flagcdn.com/w320/km.png", "aliases": []},
        {"name": "Cabo Verde", "flag": "https://flagcdn.com/w320/cv.png", "aliases": ["Cape Verde"]},
        {"name": "Sao Tome and Principe", "flag": "https://flagcdn.com/w320/st.png", "aliases": []},
        {"name": "Seychelles", "flag": "https://flagcdn.com/w320/sc.png", "aliases": []},
    ],
    "asia": [
        {"name": "China", "flag": "https://flagcdn.com/w320/cn.png", "aliases": ["PRC"]},
        {"name": "India", "flag": "https://flagcdn.com/w320/in.png", "aliases": []},
        {"name": "Indonesia", "flag": "https://flagcdn.com/w320/id.png", "aliases": []},
        {"name": "Pakistan", "flag": "https://flagcdn.com/w320/pk.png", "aliases": []},
        {"name": "Bangladesh", "flag": "https://flagcdn.com/w320/bd.png", "aliases": []},
        {"name": "Japan", "flag": "https://flagcdn.com/w320/jp.png", "aliases": []},
        {"name": "Philippines", "flag": "https://flagcdn.com/w320/ph.png", "aliases": []},
        {"name": "Vietnam", "flag": "https://flagcdn.com/w320/vn.png", "aliases": []},
        {"name": "Turkey", "flag": "https://flagcdn.com/w320/tr.png", "aliases": []},
        {"name": "Iran", "flag": "https://flagcdn.com/w320/ir.png", "aliases": []},
        {"name": "Thailand", "flag": "https://flagcdn.com/w320/th.png", "aliases": []},
        {"name": "South Korea", "flag": "https://flagcdn.com/w320/kr.png", "aliases": ["Korea"]},
        {"name": "Iraq", "flag": "https://flagcdn.com/w320/iq.png", "aliases": []},
        {"name": "Afghanistan", "flag": "https://flagcdn.com/w320/af.png", "aliases": []},
        {"name": "Saudi Arabia", "flag": "https://flagcdn.com/w320/sa.png", "aliases": []},
        {"name": "Uzbekistan", "flag": "https://flagcdn.com/w320/uz.png", "aliases": []},
        {"name": "Malaysia", "flag": "https://flagcdn.com/w320/my.png", "aliases": []},
        {"name": "Yemen", "flag": "https://flagcdn.com/w320/ye.png", "aliases": []},
        {"name": "Nepal", "flag": "https://flagcdn.com/w320/np.png", "aliases": []},
        {"name": "North Korea", "flag": "https://flagcdn.com/w320/kp.png", "aliases": ["DPRK"]},
        {"name": "Sri Lanka", "flag": "https://flagcdn.com/w320/lk.png", "aliases": []},
        {"name": "Kazakhstan", "flag": "https://flagcdn.com/w320/kz.png", "aliases": []},
        {"name": "Syria", "flag": "https://flagcdn.com/w320/sy.png", "aliases": []},
        {"name": "Cambodia", "flag": "https://flagcdn.com/w320/kh.png", "aliases": []},
        {"name": "Jordan", "flag": "https://flagcdn.com/w320/jo.png", "aliases": []},
        {"name": "Azerbaijan", "flag": "https://flagcdn.com/w320/az.png", "aliases": []},
        {"name": "United Arab Emirates", "flag": "https://flagcdn.com/w320/ae.png", "aliases": ["UAE"]},
        {"name": "Tajikistan", "flag": "https://flagcdn.com/w320/tj.png", "aliases": []},
        {"name": "Israel", "flag": "https://flagcdn.com/w320/il.png", "aliases": []},
        {"name": "Laos", "flag": "https://flagcdn.com/w320/la.png", "aliases": []},
        {"name": "Lebanon", "flag": "https://flagcdn.com/w320/lb.png", "aliases": []},
        {"name": "Kyrgyzstan", "flag": "https://flagcdn.com/w320/kg.png", "aliases": []},
        {"name": "Turkmenistan", "flag": "https://flagcdn.com/w320/tm.png", "aliases": []},
        {"name": "Singapore", "flag": "https://flagcdn.com/w320/sg.png", "aliases": []},
        {"name": "Oman", "flag": "https://flagcdn.com/w320/om.png", "aliases": []},
        {"name": "State of Palestine", "flag": "https://flagcdn.com/w320/ps.png", "aliases": ["Palestine"]},
        {"name": "Kuwait", "flag": "https://flagcdn.com/w320/kw.png", "aliases": []},
        {"name": "Georgia", "flag": "https://flagcdn.com/w320/ge.png", "aliases": []},
        {"name": "Mongolia", "flag": "https://flagcdn.com/w320/mn.png", "aliases": []},
        {"name": "Armenia", "flag": "https://flagcdn.com/w320/am.png", "aliases": []},
        {"name": "Qatar", "flag": "https://flagcdn.com/w320/qa.png", "aliases": []},
        {"name": "Bahrain", "flag": "https://flagcdn.com/w320/bh.png", "aliases": []},
        {"name": "Timor-Leste", "flag": "https://flagcdn.com/w320/tl.png", "aliases": ["East Timor", 'Timor']},
        {"name": "Cyprus", "flag": "https://flagcdn.com/w320/cy.png", "aliases": []},
        {"name": "Bhutan", "flag": "https://flagcdn.com/w320/bt.png", "aliases": []},
        {"name": "Maldives", "flag": "https://flagcdn.com/w320/mv.png", "aliases": []},
        {"name": "Brunei", "flag": "https://flagcdn.com/w320/bn.png", "aliases": []},
        {"name": "Russia", "flag": "https://flagcdn.com/w320/ru.png", "aliases": []},
    ],
    "europe": [
        {"name": "Germany", "flag": "https://flagcdn.com/w320/de.png", "aliases": []},
        {"name": "United Kingdom", "flag": "https://flagcdn.com/w320/gb.png", "aliases": ["UK", "Britain"]},
        {"name": "France", "flag": "https://flagcdn.com/w320/fr.png", "aliases": []},
        {"name": "Italy", "flag": "https://flagcdn.com/w320/it.png", "aliases": []},
        {"name": "Spain", "flag": "https://flagcdn.com/w320/es.png", "aliases": []},
        {"name": "Ukraine", "flag": "https://flagcdn.com/w320/ua.png", "aliases": []},
        {"name": "Poland", "flag": "https://flagcdn.com/w320/pl.png", "aliases": []},
        {"name": "Romania", "flag": "https://flagcdn.com/w320/ro.png", "aliases": []},
        {"name": "Netherlands", "flag": "https://flagcdn.com/w320/nl.png", "aliases": []},
        {"name": "Belgium", "flag": "https://flagcdn.com/w320/be.png", "aliases": []},
        {"name": "Czech Republic", "flag": "https://flagcdn.com/w320/cz.png", "aliases": ["Czechia"]},
        {"name": "Greece", "flag": "https://flagcdn.com/w320/gr.png", "aliases": []},
        {"name": "Portugal", "flag": "https://flagcdn.com/w320/pt.png", "aliases": []},
        {"name": "Sweden", "flag": "https://flagcdn.com/w320/se.png", "aliases": []},
        {"name": "Hungary", "flag": "https://flagcdn.com/w320/hu.png", "aliases": []},
        {"name": "Belarus", "flag": "https://flagcdn.com/w320/by.png", "aliases": []},
        {"name": "Austria", "flag": "https://flagcdn.com/w320/at.png", "aliases": []},
        {"name": "Serbia", "flag": "https://flagcdn.com/w320/rs.png", "aliases": []},
        {"name": "Switzerland", "flag": "https://flagcdn.com/w320/ch.png", "aliases": []},
        {"name": "Bulgaria", "flag": "https://flagcdn.com/w320/bg.png", "aliases": []},
        {"name": "Denmark", "flag": "https://flagcdn.com/w320/dk.png", "aliases": []},
        {"name": "Finland", "flag": "https://flagcdn.com/w320/fi.png", "aliases": []},
        {"name": "Slovakia", "flag": "https://flagcdn.com/w320/sk.png", "aliases": []},
        {"name": "Norway", "flag": "https://flagcdn.com/w320/no.png", "aliases": []},
        {"name": "Ireland", "flag": "https://flagcdn.com/w320/ie.png", "aliases": []},
        {"name": "Croatia", "flag": "https://flagcdn.com/w320/hr.png", "aliases": []},
        {"name": "Moldova", "flag": "https://flagcdn.com/w320/md.png", "aliases": []},
        {"name": "Bosnia and Herzegovina", "flag": "https://flagcdn.com/w320/ba.png", "aliases": []},
        {"name": "Albania", "flag": "https://flagcdn.com/w320/al.png", "aliases": []},
        {"name": "Lithuania", "flag": "https://flagcdn.com/w320/lt.png", "aliases": []},
        {"name": "North Macedonia", "flag": "https://flagcdn.com/w320/mk.png", "aliases": ["Macedonia"]},
        {"name": "Slovenia", "flag": "https://flagcdn.com/w320/si.png", "aliases": []},
        {"name": "Latvia", "flag": "https://flagcdn.com/w320/lv.png", "aliases": []},
        {"name": "Estonia", "flag": "https://flagcdn.com/w320/ee.png", "aliases": []},
        {"name": "Montenegro", "flag": "https://flagcdn.com/w320/me.png", "aliases": []},
        {"name": "Luxembourg", "flag": "https://flagcdn.com/w320/lu.png", "aliases": []},
        {"name": "Malta", "flag": "https://flagcdn.com/w320/mt.png", "aliases": []},
        {"name": "Iceland", "flag": "https://flagcdn.com/w320/is.png", "aliases": []},
        {"name": "Andorra", "flag": "https://flagcdn.com/w320/ad.png", "aliases": []},
        {"name": "Monaco", "flag": "https://flagcdn.com/w320/mc.png", "aliases": []},
        {"name": "Liechtenstein", "flag": "https://flagcdn.com/w320/li.png", "aliases": []},
        {"name": "San Marino", "flag": "https://flagcdn.com/w320/sm.png", "aliases": []},
        {"name": "Holy See", "flag": "https://flagcdn.com/w320/va.png", "aliases": ["Vatican City"]},
    ],
    "north_america": [
        {"name": "United States", "flag": "https://flagcdn.com/w320/us.png", "aliases": ["USA", "America"]},
        {"name": "Mexico", "flag": "https://flagcdn.com/w320/mx.png", "aliases": []},
        {"name": "Canada", "flag": "https://flagcdn.com/w320/ca.png", "aliases": []},
        {"name": "Guatemala", "flag": "https://flagcdn.com/w320/gt.png", "aliases": []},
        {"name": "Haiti", "flag": "https://flagcdn.com/w320/ht.png", "aliases": []},
        {"name": "Cuba", "flag": "https://flagcdn.com/w320/cu.png", "aliases": []},
        {"name": "Dominican Republic", "flag": "https://flagcdn.com/w320/do.png", "aliases": []},
        {"name": "Honduras", "flag": "https://flagcdn.com/w320/hn.png", "aliases": []},
        {"name": "El Salvador", "flag": "https://flagcdn.com/w320/sv.png", "aliases": []},
        {"name": "Nicaragua", "flag": "https://flagcdn.com/w320/ni.png", "aliases": []},
        {"name": "Costa Rica", "flag": "https://flagcdn.com/w320/cr.png", "aliases": []},
        {"name": "Panama", "flag": "https://flagcdn.com/w320/pa.png", "aliases": []},
        {"name": "Jamaica", "flag": "https://flagcdn.com/w320/jm.png", "aliases": []},
        {"name": "Trinidad and Tobago", "flag": "https://flagcdn.com/w320/tt.png", "aliases": []},
        {"name": "Bahamas", "flag": "https://flagcdn.com/w320/bs.png", "aliases": []},
        {"name": "Belize", "flag": "https://flagcdn.com/w320/bz.png", "aliases": []},
        {"name": "Barbados", "flag": "https://flagcdn.com/w320/bb.png", "aliases": []},
        {"name": "Saint Lucia", "flag": "https://flagcdn.com/w320/lc.png", "aliases": []},
        {"name": "Grenada", "flag": "https://flagcdn.com/w320/gd.png", "aliases": []},
        {"name": "Saint Vincent and the Grenadines", "flag": "https://flagcdn.com/w320/vc.png", "aliases": []},
        {"name": "Antigua and Barbuda", "flag": "https://flagcdn.com/w320/ag.png", "aliases": []},
        {"name": "Saint Kitts and Nevis", "flag": "https://flagcdn.com/w320/kn.png", "aliases": []},
        {"name": "Dominica", "flag": "https://flagcdn.com/w320/dm.png", "aliases": []},
    ],
    "south_america": [
        {"name": "Brazil", "flag": "https://flagcdn.com/w320/br.png", "aliases": []},
        {"name": "Colombia", "flag": "https://flagcdn.com/w320/co.png", "aliases": []},
        {"name": "Argentina", "flag": "https://flagcdn.com/w320/ar.png", "aliases": []},
        {"name": "Peru", "flag": "https://flagcdn.com/w320/pe.png", "aliases": []},
        {"name": "Venezuela", "flag": "https://flagcdn.com/w320/ve.png", "aliases": []},
        {"name": "Chile", "flag": "https://flagcdn.com/w320/cl.png", "aliases": []},
        {"name": "Ecuador", "flag": "https://flagcdn.com/w320/ec.png", "aliases": []},
        {"name": "Bolivia", "flag": "https://flagcdn.com/w320/bo.png", "aliases": []},
        {"name": "Paraguay", "flag": "https://flagcdn.com/w320/py.png", "aliases": []},
        {"name": "Uruguay", "flag": "https://flagcdn.com/w320/uy.png", "aliases": []},
        {"name": "Guyana", "flag": "https://flagcdn.com/w320/gy.png", "aliases": []},
        {"name": "Suriname", "flag": "https://flagcdn.com/w320/sr.png", "aliases": []},
    ],
    "oceania": [
        {"name": "Australia", "flag": "https://flagcdn.com/w320/au.png", "aliases": []},
        {"name": "Papua New Guinea", "flag": "https://flagcdn.com/w320/pg.png", "aliases": []},
        {"name": "New Zealand", "flag": "https://flagcdn.com/w320/nz.png", "aliases": []},
        {"name": "Fiji", "flag": "https://flagcdn.com/w320/fj.png", "aliases": []},
        {"name": "Solomon Islands", "flag": "https://flagcdn.com/w320/sb.png", "aliases": []},
        {"name": "Micronesia", "flag": "https://flagcdn.com/w320/fm.png", "aliases": []},
        {"name": "Vanuatu", "flag": "https://flagcdn.com/w320/vu.png", "aliases": []},
        {"name": "Samoa", "flag": "https://flagcdn.com/w320/ws.png", "aliases": []},
        {"name": "Kiribati", "flag": "https://flagcdn.com/w320/ki.png", "aliases": []},
        {"name": "Tonga", "flag": "https://flagcdn.com/w320/to.png", "aliases": []},
        {"name": "Marshall Islands", "flag": "https://flagcdn.com/w320/mh.png", "aliases": []},
        {"name": "Palau", "flag": "https://flagcdn.com/w320/pw.png", "aliases": []},
        {"name": "Tuvalu", "flag": "https://flagcdn.com/w320/tv.png", "aliases": []},
        {"name": "Nauru", "flag": "https://flagcdn.com/w320/nr.png", "aliases": []},
    ],
    "test": [
        {"name": "Australia", "flag": "https://flagcdn.com/w2560/au.png", "aliases": []},
        {"name": "Brazil", "flag": "https://flagcdn.com/w2560/br.png", "aliases": []},
        {"name": "Colombia", "flag": "https://flagcdn.com/w2560/co.png", "aliases": []},
        {"name": "Argentina", "flag": "https://flagcdn.com/w2560/ar.png", "aliases": []},
    ],
    "most_popular": [
        {"name": "Australia", "flag": "https://flagcdn.com/w320/au.png", "aliases": []},
        {"name": "Brazil", "flag": "https://flagcdn.com/w320/br.png", "aliases": []},
        {"name": "United States", "flag": "https://flagcdn.com/w320/us.png", "aliases": ["USA", "America"]},
        {"name": "Argentina", "flag": "https://flagcdn.com/w320/ar.png", "aliases": []},
        {"name": "Mexico", "flag": "https://flagcdn.com/w320/mx.png", "aliases": []},
        {"name": "Canada", "flag": "https://flagcdn.com/w320/ca.png", "aliases": []},
        {"name": "Germany", "flag": "https://flagcdn.com/w320/de.png", "aliases": []},
        {"name": "United Kingdom", "flag": "https://flagcdn.com/w320/gb.png", "aliases": ["UK", "Britain"]},
        {"name": "France", "flag": "https://flagcdn.com/w320/fr.png", "aliases": []},
        {"name": "Italy", "flag": "https://flagcdn.com/w320/it.png", "aliases": []},
        {"name": "Spain", "flag": "https://flagcdn.com/w320/es.png", "aliases": []},
        {"name": "China", "flag": "https://flagcdn.com/w320/cn.png", "aliases": ["PRC"]},
        {"name": "India", "flag": "https://flagcdn.com/w320/in.png", "aliases": []},
        {"name": "Japan", "flag": "https://flagcdn.com/w320/jp.png", "aliases": []},
        {"name": "Russia", "flag": "https://flagcdn.com/w320/ru.png", "aliases": []},
        {"name": "South Korea", "flag": "https://flagcdn.com/w320/kr.png", "aliases": ["Korea"]},
        {"name": "Sweden", "flag": "https://flagcdn.com/w320/se.png", "aliases": []},
        {"name": "Greece", "flag": "https://flagcdn.com/w320/gr.png", "aliases": []},
        {"name": "Switzerland", "flag": "https://flagcdn.com/w320/ch.png", "aliases": []},
        {"name": "Israel", "flag": "https://flagcdn.com/w320/il.png", "aliases": []},
    ]
}


def replace_flag_resolution_with_one_line(countries_by_continent):
    # Iterate over each continent in the dictionary
    for continent, countries in countries_by_continent.items():
        # Iterate over each country in the continent's list
        for country in countries:
            # Replace "320" with "2560" in the flag URL
            country['flag'] = country['flag'].replace("w320", "w2560")

    # Return the updated dictionary in a custom formatted JSON-like string with each country on one line
    result = "{\n"
    for continent, countries in countries_by_continent.items():
        result += f'    "{continent}": [\n'
        for country in countries:
            country_str = json.dumps(country)
            result += f'        {country_str},\n'
        result = result.rstrip(",\n") + "\n    ],\n"  # Remove trailing comma for the last country
    result = result.rstrip(",\n") + "\n}"

    return result


# Example usage
formatted_countries_by_continent = replace_flag_resolution_with_one_line(countries_by_continent)
print(formatted_countries_by_continent)